INSERT INTO feedback (id, text, created_at, sentiment, confidence_json, key_phrases_json)
VALUES (1,
        'Das Produkt hat meine Erwartungen bei weitem übertroffen! Die Qualität ist hervorragend und die Lieferung kam sogar früher als geplant. Ich bin absolut begeistert.',
        now(), 'POSITIVE', '{"POSITIVE":0.97,"NEGATIVE":0.01,"NEUTRAL":0.01, "MIXED":0.01}',
        '["hervorragende Qualität","frühere Lieferung","absolut begeistert"]'),
       (2,
        'Leider war der Kundensupport sehr enttäuschend. Ich habe dreimal angerufen und niemand konnte mir helfen. Das Problem ist immer noch nicht gelöst.',
        now(), 'NEGATIVE', '{"POSITIVE":0.01,"NEGATIVE":0.95,"NEUTRAL":0.02,"MIXED":0.02}',
        '["Kundensupport","enttäuschend","Problem nicht gelöst"]'),
       (3, 'Ich habe das Gerät gestern erhalten. Es funktioniert wie beschrieben. Die Verpackung war in Ordnung.',
        now() - interval '1 day', 'NEUTRAL', '{"POSITIVE":0.15,"NEGATIVE":0.05,"NEUTRAL":0.76,"MIXED":0.04}',
        '["Gerät erhalten","wie beschrieben","Verpackung"]'),
       (4,
        'Das Design ist wirklich schön und modern, aber die Akkulaufzeit ist eine Katastrophe. Kaum 4 Stunden – das ist absolut nicht akzeptabel.',
        now() - interval '1 day', 'MIXED', '{"POSITIVE":0.28,"NEGATIVE":0.32,"NEUTRAL":0.08,"MIXED":0.62}',
        '["schönes Design","Akkulaufzeit","nicht akzeptabel"]'),
       (5, 'Fantastisches Preis-Leistungs-Verhältnis! Schnelle Lieferung, einfache Montage. Kaufe hier gerne wieder.',
        now() - interval '2 days', 'POSITIVE', '{"POSITIVE":0.94,"NEGATIVE":0.01,"NEUTRAL":0.02,"MIXED":0.03}',
        '["Preis-Leistungs-Verhältnis","schnelle Lieferung","einfache Montage"]'),
       (6,
        'Die App stürzt ständig ab. Schon drei Mal heute. Das ist frustrierend und macht die Nutzung unmöglich. Bitte dringend fixen!',
        now() - interval '2 days', 'NEGATIVE', '{"POSITIVE":0.01,"NEGATIVE":0.97,"NEUTRAL":0.01,"MIXED":0.01}',
        '["App stürzt ab","frustrierend","dringend fixen"]'),
       (7, 'Lieferzeit war wie angegeben. Produkt entspricht der Beschreibung. Nichts Besonderes.',
        now() - interval '3 days', 'NEUTRAL', '{"POSITIVE":0.10,"NEGATIVE":0.06,"NEUTRAL":0.79,"MIXED":0.05}',
        '["Lieferzeit","Produktbeschreibung"]'),
       (8,
        'Sehr freundlicher Service am Telefon, aber das zugesagte Rückruf kam nie. Das ist ärgerlich, auch wenn das Gespräch angenehm war.',
        now() - interval '3 days', 'MIXED', '{"POSITIVE":0.31,"NEGATIVE":0.25,"NEUTRAL":0.06,"MIXED":0.58}',
        '["freundlicher Service","Rückruf","ärgerlich"]'),
       (9,
        'Ich bin seit Jahren Kunde und war immer zufrieden. Dieses Mal hat alles perfekt geklappt – wieder einmal. Danke für die konstant hohe Qualität!',
        now() - interval '4 days', 'POSITIVE', '{"POSITIVE":0.96,"NEGATIVE":0.01,"NEUTRAL":0.02,"MIXED":0.01}',
        '["Jahre Kunde","zufrieden","konstant hohe Qualität"]'),
       (10,
        'Das Gerät kam beschädigt an. Die Verpackung war bereits offen und das Display hat einen Riss. Totale Enttäuschung. Retoure läuft.',
        now() - interval '4 days', 'NEGATIVE', '{"POSITIVE":0.01,"NEGATIVE":0.98,"NEUTRAL":0.01,"MIXED":0.00}',
        '["beschädigt","Verpackung offen","Display Riss"]'),
       (11, 'Gute Qualität für den Preis. Würde ich wieder kaufen.', now() - interval '5 days', 'POSITIVE',
        '{"POSITIVE":0.82,"NEGATIVE":0.03,"NEUTRAL":0.12,"MIXED":0.03}', '["gute Qualität","Preis"]'),
       (12, 'Bestellung aufgegeben. Wird geliefert.', now() - interval '5 days', 'NEUTRAL',
        '{"POSITIVE":0.05,"NEGATIVE":0.04,"NEUTRAL":0.88,"MIXED":0.03}', '["Bestellung","Lieferung"]'),
       (13,
        'Hervorragender Support! Das Problem wurde innerhalb von 10 Minuten gelöst. So stellt man sich Kundenservice vor. Absolute Empfehlung!',
        now() - interval '6 days', 'POSITIVE', '{"POSITIVE":0.99,"NEGATIVE":0.00,"NEUTRAL":0.00,"MIXED":0.01}',
        '["hervorragender Support","10 Minuten","Kundenservice"]');